# Generated by Django 5.1.1 on 2024-09-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertise',
            name='icon',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
