# Generated by Django 5.1.1 on 2024-09-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='image',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='url',
            field=models.URLField(),
        ),
    ]
